//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_ATM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public A_ATM()
        {
            this.ATMs = new HashSet<ATM>();
        }
    
        public int a_admin_id { get; set; }
        public string a_admin_name { get; set; }
        public string a_admin_pin { get; set; }
        public string a_admin_rights { get; set; }
        public Nullable<int> a_branch_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATM> ATMs { get; set; }
        public virtual ATM ATM { get; set; }
    }
}
