//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBank
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    public partial class ATM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATM()
        {
            this.A_ATM1 = new HashSet<A_ATM>();
        }
    
        public int a_branch_id { get; set; }
        [Required(ErrorMessage ="Branch name is mandatory")]
        public string a_branch_name { get; set; }
        [Required(ErrorMessage = "Branch address is mandatory")]
        public string a_branch_add { get; set; }
        public int a_admin_id { get; set; }
        [Required(ErrorMessage = "Available cash is mandatory")]
        //[RegularExpression(@"^(?!\.?$)\d{0,5}(\.\d{0,2})?$", ErrorMessage = "Numbers only, max is 99999")]
        public decimal available_cash { get; set; }
        public int b_branch_id { get; set; }
    
        public virtual A_ATM A_ATM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<A_ATM> A_ATM1 { get; set; }
        public virtual Bank Bank { get; set; }
    }
}
